RP/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from RP import views, settings

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('cr/', include('cr.urls')),
    path('home/', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ratings/', include('ratings.urls', namespace='ratings')),
    path('searchings/', include('searchings.urls', namespace='searchings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, re_path
from accounts import views
from django.contrib.auth.views import (login, logout,
                                       password_reset,
                                       password_reset_done,
                                       password_reset_confirm,
                                       password_reset_complete
                                       )

app_name = "accounts"
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', login, {'template_name': 'accounts/login.html',
                           'redirect_field_name': '/accounts/register/'}, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('reset-password/', password_reset, {'template_name': 'accounts/reset_password.html',
                                             'post_reset_redirect': 'accounts:password_reset_done',
                                             'email_template_name': 'accounts/reset_password_email.html'},
         name='reset_password'),
    path('reset-password-done/', password_reset_done, {"template_name": 'accounts/reset_password_done.html'},
         name='password_reset_done'),
    path('reset-password/confirm/?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/',
         password_reset_confirm, {"template_name": 'accounts/reset_password_confirm.html',
                                  'post_reset_redirect': 'accounts:password_reset_complete'},
         name='password_reset_confirm'),
    path('reset-password/complete/', password_reset_complete,
         {"template_name": 'accounts/reset_password_complete.html'},
         name='password_reset_complete'),
]

cr/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:student_id>/info', views.registed, name='registed'),
    path('<int:student_id>/', views.register, name='register'),
]

searchings/urls.py
from django.urls import path

from . import views

app_name = 'searchings'
urlpatterns = [
    path('<int:professor_id>/<str:professor_name>/', views.professor, name='professor'),
    path('school/<str:professor_school>/', views.school_filter, name='school_filter'),
    path('prof/<str:professor_name>/', views.professor_filter, name='professor_filter'),
    path('school_prof/<str:professor_school>/', views.school_professor_filter,
         name='school_professor_filter'),
    path('college_prof/<str:professor_college>/', views.college_professor_filter,
         name='college_professor_filter'),
]

searchings/models.py
from django.db import models
from django.contrib.auth.models import User


class Professor(models.Model):
    prof_name = models.CharField(max_length=30)
    prof_introduction = models.TextField()
    prof_school = models.ManyToManyField('School')
    prof_college = models.ManyToManyField('College')

    def __str__(self):
        return str(self.prof_name)


class School(models.Model):
    school_name = models.CharField(max_length=20)
    school_location = models.CharField(max_length=20, default='')
    school_introduction = models.TextField()

    def __str__(self):
        return self.school_name

    def __unicode__(self):
        return self.school_name


class College(models.Model):
    college_name = models.CharField(max_length=20)
    college_introduction = models.TextField()

    def __str__(self):
        return str(self.college_name)


class Major(models.Model):
    major_name = models.CharField(max_length=20)

    def __str__(self):
        return str(self.major_name)


class GeneralClass(models.Model):
    class_name = models.CharField(max_length=20)
    class_prof = models.ManyToManyField(Professor)
    class_college = models.ForeignKey(College, on_delete=models.CASCADE)
    class_major = models.ForeignKey("Major", on_delete=models.CASCADE)
    class_introduction = models.TextField()
    class_prerequisite = models.CharField(max_length=20)
    class_type = models.CharField(max_length=20)
    class_credit = models.FloatField()

    def __str__(self):
        return str(self.class_name)


class SpecificClass(models.Model):
    class_introduction = models.ForeignKey(GeneralClass, on_delete=models.CASCADE)
    class_section = models.IntegerField()
    class_code = models.IntegerField()
    class_period = models.CharField(max_length=20)
    class_remain_seat = models.IntegerField()

    def __str__(self):
        return self.class_introduction.class_name + '\n' + \
               str(self.class_introduction.class_prof) + '\n' + \
               str(self.class_introduction.class_college) + '\n' + \
               str(self.class_introduction.class_introduction) + '\n' + \
               str(self.class_section) + str(self.class_code) + '\n' + \
               str(self.class_remain_seat)


class Rating(models.Model):
    attendance_choices = (
        ('未知', "it's still a secret"),
        ('每周必点', "100% take attendance"),
        ('人少就点', "if there seems like not enough people"),
        ('基本不管', "doesn't really care the attendance"),
        ('纯看心情', "depends on the days or professor's mood"),
    )
    overall_rating = models.FloatField()
    overall_difficulty_number = models.FloatField()
    class_graded = models.CharField(max_length=5)
    overall_difficulty = models.CharField(max_length=100)
    overall_looking = models.CharField(max_length=20)
    attendance_requirement = models.CharField(max_length=30, choices=attendance_choices, default="未知")
    prof_personality_tag = models.CharField(max_length=50, null=True)
    student_learning_tag = models.CharField(max_length=50, null=True)
    class_atmosphere_tag = models.CharField(max_length=30, null=True)
    homework_requirement_tag = models.CharField(max_length=30, null=True)
    teaching_style_tag = models.CharField(max_length=30, null=True)
    prof_rating = models.ForeignKey('Professor', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.overall_rating) + '\n' + \
               str(self.overall_difficulty) + '\n' + \
               str(self.overall_looking) + '\n' + \
               str(self.class_graded) + '\n' + \
               str(self.attendance_requirement) + '\n' + \
               str(self.prof_personality_tag) + '\n' + \
               str(self.student_learning_tag) + '\n' + \
               str(self.class_atmosphere_tag) + '\n' + \
               str(self.homework_requirement_tag) + '\n' + \
               str(self.teaching_style_tag)


class Post(models.Model):
    post = models.TextField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    rating_post = models.ForeignKey('Rating', on_delete=models.CASCADE)

    def __str__(self):
        return self.post

searchings/forms.py
from django import forms
from .models import Post


class ProfessorForm(forms.ModelForm):
    post = forms.TextInput()

    class Meta:
        model = Post
        fields = ('post',)

searchings/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from home.forms import HomeForm
from searchings.forms import ProfessorForm
from searchings.models import Post, Professor, School, Rating, College


def professor(request, professor_id, professor_name):
    if request.method == "GET":
        form = HomeForm()
        print(form)
        prof = Professor.objects.get(id=professor_id)
        ratings = Rating.objects.filter(prof_rating=prof).order_by('-date')
        total = len(ratings)
        overall_grade = 0.0
        for score in ratings:
            overall_grade += score.overall_rating
        if total == 0:
            overall_grade = 0
        else:
            overall_grade = overall_grade / total
        overall_grade = round(overall_grade, 2)
        total_rating_user = len(ratings)
        posts = Post.objects.filter(rating_post__in=ratings).order_by('-date')
        args = {'form': form,
                'posts': posts,
                'prof': prof,
                'ratings': ratings,
                'overall_grade': overall_grade,
                'total_rating_user': total_rating_user,
                }
        return render(request, 'searchings/professor.html', args)

    if request.method == 'POST':
        form = HomeForm(request.POST)
        if form.is_valid():
            search = form.save(commit=False)
            search.save()
            school = form.cleaned_data['school']
            prof = form.cleaned_data['prof']
            college = form.cleaned_data['college']
            if school != '' and prof == '' and college == '':
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(school,)))
            elif school == '' and prof != '' and college == '':
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(prof,)))
            elif school == '' and prof == '' and college != '':
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(college,)))
            else:
                post = form.save(commit=False)
                post.user = request.user
                prof = Professor.objects.get(id=professor_id,
                                             prof_name=professor_name)

                ratings = Rating.objects.filter(prof_rating=prof).order_by('-date')
                for rating in ratings:
                    post.rating_post = rating
                post.save()
                args = {'form': form,
                        'prof': prof,
                        'ratings': ratings
                        }
                return render(request, 'searchings/professor.html', args)
        else:
            return redirect(reverse('searchings:professor', args=(professor_id, professor_name,)))


def professor_filter(request, professor_name):
    if request.method == "GET":
        form = HomeForm()
        profs = Professor.objects.filter(prof_name=professor_name)
        args = {'form': form,
                'profs': profs
                }
        if len(profs) == 0:
            profs = Professor.objects.filter(prof_name__startswith=professor_name)
            args = {'form': form,
                    'profs': profs,
                    }
            return render(request, 'searchings/professor_filter.html', args)
        if len(profs) > 1:
            return render(request, 'searchings/professor_filter.html', args)
        else:
            prof = Professor.objects.get(prof_name=professor_name)
            return HttpResponseRedirect(reverse('searchings:professor', args=(prof.id, professor_name,)))
    if request.method == 'POST':
        form = HomeForm(request.POST)
        if form.is_valid():
            search = form.save(commit=False)
            search.save()
            school = form.cleaned_data['school']
            prof = form.cleaned_data['prof']
            college = form.cleaned_data['college']
            if school != '' and prof == '' and college == '':
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(school,)))
            elif school == '' and prof != '' and college == '':
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(prof,)))
            elif school == '' and prof == '' and college != '':
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(college,)))
            else:
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(professor_name,)))


def school_filter(request, professor_school):
    if request.method == "GET":
        form = HomeForm()
        schools = School.objects.filter(school_name__startswith=professor_school)
        args = {'form': form,
                'schools': schools,
                }
        return render(request, 'searchings/school_filter.html', args)
    if request.method == 'POST':
        form = HomeForm(request.POST)
        if form.is_valid():
            search = form.save(commit=False)
            search.save()
            school = form.cleaned_data['school']
            prof = form.cleaned_data['prof']
            college = form.cleaned_data['college']
            if school != '' and prof == '' and college == '':
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(school,)))
            elif school == '' and prof != '' and college == '':
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(prof,)))
            elif school == '' and prof == '' and college != '':
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(college,)))
            else:
                return HttpResponseRedirect(reverse('searchings:school_filter', args=(professor_school,)))


def school_professor_filter(request, professor_school):
    if request.method == "GET":
        form = HomeForm()
        school = School.objects.filter(school_name__startswith=professor_school)
        profs = Professor.objects.filter(prof_school__in=school)
        args = {'form': form,
                'profs': profs
                }
        return render(request, 'searchings/professor_filter.html', args)
    if request.method == 'POST':
        form = HomeForm(request.POST)
        if form.is_valid():
            search = form.save(commit=False)
            search.save()
            school = form.cleaned_data['school']
            prof = form.cleaned_data['prof']
            college = form.cleaned_data['college']
            if school != '' and prof == '' and college == '':
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(school,)))
            elif school == '' and prof != '' and college == '':
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(prof,)))
            elif school == '' and prof == '' and college != '':
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(college,)))
            else:
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(professor_school,)))


def college_professor_filter(request, professor_college):
    if request.method == "GET":
        form = HomeForm()
        college = College.objects.filter(college_name__startswith=professor_college)
        profs = Professor.objects.filter(prof_college__in=college)
        args = {'form': form,
                'profs': profs
                }
        return render(request, 'searchings/professor_filter.html', args)
    if request.method == 'POST':
        form = HomeForm(request.POST)
        if form.is_valid():
            search = form.save(commit=False)
            search.save()
            school = form.cleaned_data['school']
            prof = form.cleaned_data['prof']
            college = form.cleaned_data['college']
            if school != '' and prof == '' and college == '':
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(school,)))
            elif school == '' and prof != '' and college == '':
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(prof,)))
            elif school == '' and prof == '' and college != '':
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(college,)))
            else:
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(professor_college,)))

searchings/templates/base_search.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block head %}
        <title>象牙</title>
    {% endblock %}

    {% load static %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'searchings/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'searchings/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'searchings/dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static 'searchings/vendor/morrisjs/morris.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'searchings/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet"
          type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}
    {% endblock %}

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:index' %}">象牙</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-messages">
                    <li>
                        <a href="#">
                            <div>
                                <strong>John Smith</strong>
                                <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                            </div>
                            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <strong>John Smith</strong>
                                <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                            </div>
                            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <strong>John Smith</strong>
                                <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                            </div>
                            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text-center" href="#">
                            <strong>Read All Messages</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
                <!-- /.dropdown-messages -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-comment fa-fw"></i> New Comment
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                <span class="pull-right text-muted small">12 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-envelope fa-fw"></i> Message Sent
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-tasks fa-fw"></i> New Task
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                <span class="pull-right text-muted small">4 minutes ago</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text-center" href="#">
                            <strong>See All Alerts</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
                <!-- /.dropdown-alerts -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="#"><i class="fa fa-search fa-fw"></i>通过学校名字搜索</a>
                        <ul class="nav nav-second-level">
                            <li class="sidebar-search">
                                <form method="POST" autocomplete="off">
                                    {% csrf_token %}
                                    <div class="input-group custom-search-form">
                                        <label for="school" class="sr-only">School</label>
                                        <input type="text" name="school" id="school" class="school"
                                               autocomplete="off" spellcheck="false"
                                               placeholder="school">
                                        <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                                    </div>
                                </form>
                                <!-- /input-group -->
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-search fa-fw"></i>通过教师名字搜索</a>
                        <ul class="nav nav-second-level">
                            <li class="sidebar-search">
                                <form method="POST" autocomplete="off">
                                    {% csrf_token %}
                                    <div class="input-group custom-search-form">
                                        <label for="prof" class="sr-only">Professor</label>
                                        <input type="text" name="prof" id="prof" class="prof tt-query"
                                               autocomplete="off"
                                               spellcheck="false"
                                               placeholder="prof">
                                        <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                                    </div>
                                </form>
                                <!-- /input-group -->
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-search fa-fw"></i>通过学院名字搜索></a>
                        <ul class="nav nav-second-level">
                            <li class="sidebar-search">
                                <form method="POST" autocomplete="off">
                                    {% csrf_token %}
                                    <div class="input-group custom-search-form">
                                        <label for="college" class="sr-only">College</label>
                                        <input type="text" name="college" id="college" class="college"
                                               autocomplete="off"
                                               spellcheck="false"
                                               placeholder="college">
                                        <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                                    </div>
                                </form>
                                <!-- /input-group -->
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>


</div>

<!-- /#wrapper -->
{% block body %}
{% endblock %}

<!-- jQuery -->
<script src="{% static 'searchings/vendor/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'searchings/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'searchings/vendor/metisMenu/metisMenu.min.js' %}"></script>

<!-- Morris Charts JavaScript -->
<script src="{% static 'searchings/vendor/raphael/raphael.min.js' %}"></script>
<script src="{% static 'searchings/vendor/morrisjs/morris.min.js' %}"></script>
<script src="{% static 'searchings/data/morris-data.js' %}"></script>

{% block js %}
{% endblock %}

<!-- Custom Theme JavaScript -->
<script src="{% static 'searchings/dist/js/sb-admin-2.js' %}"></script>

</body>

</html>