RP/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from RP import views, settings

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('cr/', include('cr.urls')),
    path('home/', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ratings/', include('ratings.urls', namespace='ratings')),
    path('searchings/', include('searchings.urls', namespace='searchings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, re_path
from accounts import views
from django.contrib.auth.views import (login, logout,
                                       password_reset,
                                       password_reset_done,
                                       password_reset_confirm,
                                       password_reset_complete
                                       )

app_name = "accounts"
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', login, {'template_name': 'accounts/login.html',
                           'redirect_field_name': '/accounts/register/'}, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('reset-password/', password_reset, {'template_name': 'accounts/reset_password.html',
                                             'post_reset_redirect': 'accounts:password_reset_done',
                                             'email_template_name': 'accounts/reset_password_email.html'},
         name='reset_password'),
    path('reset-password-done/', password_reset_done, {"template_name": 'accounts/reset_password_done.html'},
         name='password_reset_done'),
    path('reset-password/confirm/?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/',
         password_reset_confirm, {"template_name": 'accounts/reset_password_confirm.html',
                                  'post_reset_redirect': 'accounts:password_reset_complete'},
         name='password_reset_confirm'),
    path('reset-password/complete/', password_reset_complete,
         {"template_name": 'accounts/reset_password_complete.html'},
         name='password_reset_complete'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2'
                  )

    # def save(self, commit=True):
    #     user = super(RegistrationForm, self).save(commit=False)
    #     user.first_name = self.cleaned_data['first_name']
    #     user.last_name = self.cleaned_data['last_name']
    #     user.email = self.cleaned_data['email']
    #
    #     if commit:
    #         user.save()
    #
    #     return user


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import RegistrationForm, EditProfileForm
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login


def index(request):
    return render(request, 'base.html')


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts/')
    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)


@login_required
def profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)


@login_required
def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/accounts/profile')
        else:
            return redirect('/accounts/change-password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)


def logout_view(request):
    logout(request)
    return redirect('home:index')

#
# def my_view(request):
#     print(request.POST)
#     username = request.POST['Username']
#     password = request.POST['Password']
#     user = authenticate(request, username=username, password=password)
#     if user is not None:
#         login(request, user)
#         return redirect('home:index')
#
#     else:
#         return "Haven't register yet?"

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block head %}
    <title>Profile</title>
{% endblock %}

{% block body %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block head %}
    <title>Profile</title>
{% endblock %}

{% block body %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}

{% block body %}
{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    {#    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>#}
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    {#    <script>#}
    {#        function showPassword() {#}
    {##}
    {#            var key_attr = $('#key').attr('type');#}
    {##}
    {#            if (key_attr != 'text') {#}
    {##}
    {#                $('.checkbox').addClass('show');#}
    {#                $('#key').attr('type', 'text');#}
    {##}
    {#            } else {#}
    {##}
    {#                $('.checkbox').removeClass('show');#}
    {#                $('#key').attr('type', 'password');#}
    {##}
    {#            }#}
    {##}
    {#        }#}
    {#    </script>#}
    <style>
        /*    --------------------------------------------------
	:: Login Section
	-------------------------------------------------- */
        #login {
            padding-top: 50px
        }

        #login .form-wrap {
            width: 30%;
            margin: 0 auto;
        }

        #login h1 {
            color: #1fa67b;
            font-size: 18px;
            text-align: center;
            font-weight: bold;
            padding-bottom: 20px;
        }

        #login .form-group {
            margin-bottom: 25px;
        }

        #login .checkbox {
            margin-bottom: 20px;
            position: relative;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            -o-user-select: none;
            user-select: none;
        }

        #login .checkbox.show:before {
            content: '\e013';
            color: #1fa67b;
            font-size: 17px;
            margin: 1px 0 0 3px;
            position: absolute;
            pointer-events: none;
            font-family: 'Glyphicons Halflings';
        }

        #login .checkbox .character-checkbox {
            width: 25px;
            height: 25px;
            cursor: pointer;
            border-radius: 3px;
            border: 1px solid #ccc;
            vertical-align: middle;
            display: inline-block;
        }

        #login .checkbox .label {
            color: #6d6d6d;
            font-size: 13px;
            font-weight: normal;
        }

        #login .btn.btn-custom {
            font-size: 14px;
            margin-bottom: 20px;
        }

        #login .forget {
            font-size: 13px;
            text-align: center;
            display: block;
        }

        /*    --------------------------------------------------
            :: Inputs & Buttons
            -------------------------------------------------- */
        .form-control {
            color: #212121;
        }

        .btn-custom {
            color: #fff;
            background-color: #1fa67b;
        }

        .btn-custom:hover,
        .btn-custom:focus {
            color: #fff;
        }

        /*    --------------------------------------------------
            :: Footer
            -------------------------------------------------- */
        #footer {
            color: #6d6d6d;
            font-size: 12px;
            text-align: center;
        }

        #footer p {
            margin-bottom: 0;
        }

        #footer a {
            color: inherit;
        }
    </style>
</head>

<body>
<section id="login">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="form-wrap">
                    <h1>Log in with your account</h1>
                    {% if form.errors %}
                        <h5>username or password not correct</h5>
                    {% endif %}
                    <form method="POST" action="{% url 'accounts:login' %}" id="login-form" autocomplete="off">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="sr-only">Username</label>
                            <input type="text" name="username" id="username" class="form-control"
                                   placeholder="Username">
                        </div>
                        <div class="form-group">
                            <label for="password" class="sr-only">Password</label>
                            <input type="password" name="password" id="password" class="form-control"
                                   placeholder="Password">
                        </div>
                        <button type="submit" id="btn-login" class="btn btn-custom btn-lg btn-block">Log in</button>
                    </form>
                    <a href="http://localhost:8000/accounts/reset-password/" class="forget" data-toggle="modal"
                       data-target=".forget-modal">Forgot
                        your password?</a>
                    <hr>
                </div>
            </div> <!-- /.col-xs-12 -->
        </div> <!-- /.row -->
    </div> <!-- /.container -->
</section>

{#<div class="modal fade forget-modal" tabindex="-1" role="dialog" aria-labelledby="myForgetModalLabel"#}
{#     aria-hidden="true">#}
{#    <div class="modal-dialog modal-sm">#}
{#        <div class="modal-content">#}
{#            <div class="modal-header">#}
{#                <button type="button" class="close" data-dismiss="modal">#}
{#                    <span aria-hidden="true">×</span>#}
{#                    <span class="sr-only">Close</span>#}
{#                </button>#}
{#                <h4 class="modal-title">Recovery password</h4>#}
{#            </div>#}
{#            <div class="modal-body">#}
{#                <p>Type your email account</p>#}
{#                <input type="email" name="recovery-email" id="recovery-email" class="form-control" autocomplete="off">#}
{#            </div>#}
{#            <div class="modal-footer">#}
{#                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>#}
{#                <button type="button" class="btn btn-custom">Recovery</button>#}
{#            </div>#}
{#        </div> <!-- /.modal-content -->#}
{#    </div> <!-- /.modal-dialog -->#}
{#</div> <!-- /.modal -->#}

<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <p>Page © - 2018</p>
                <p>Powered by <strong><a href="http://www.facebook.com/tavo.qiqe.lucero"
                                         target="_blank">象牙网络科技公司</a></strong></p>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}

{% block body %}
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block head %}
    <title>Profile</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/picture.css' %}" type="text/css">
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Profile</h1>
        <p>Username: {{ user }}</p>
        <p>Firstname: {{ user.first_name }}</p>
        <p>Lastname: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Student id: {{ user.student.school_id }}</p>
        <p>School Name: {{ user.student.school_name }}</p>
        <a href="http://localhost:8000/accounts/change-password/" class="btn btn-primary btn-sm active"
           role="button" aria-pressed="true">Password Reset</a>
        <a href="http://localhost:8000/accounts/profile/edit" class="btn btn-primary btn-sm active"
           role="button" aria-pressed="true">Profile Update</a>
    </div>
    <div class="picture">
        <img src="{{ user.student.student_image.url }}" width="240">
    </div>
{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <h1>Register</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    {#    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>#}
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <style>
        /*    --------------------------------------------------
	:: Login Section
	-------------------------------------------------- */
        #login {
            padding-top: 50px
        }

        #login .form-wrap {
            width: 30%;
            margin: 0 auto;
        }

        #login h1 {
            color: #1fa67b;
            font-size: 18px;
            text-align: center;
            font-weight: bold;
            padding-bottom: 20px;
        }

        #login .form-group {
            margin-bottom: 25px;
        }

        #login .checkbox {
            margin-bottom: 20px;
            position: relative;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            -o-user-select: none;
            user-select: none;
        }

        #login .checkbox.show:before {
            content: '\e013';
            color: #1fa67b;
            font-size: 17px;
            margin: 1px 0 0 3px;
            position: absolute;
            pointer-events: none;
            font-family: 'Glyphicons Halflings';
        }

        #login .checkbox .character-checkbox {
            width: 25px;
            height: 25px;
            cursor: pointer;
            border-radius: 3px;
            border: 1px solid #ccc;
            vertical-align: middle;
            display: inline-block;
        }

        #login .checkbox .label {
            color: #6d6d6d;
            font-size: 13px;
            font-weight: normal;
        }

        #login .btn.btn-custom {
            font-size: 14px;
            margin-bottom: 20px;
        }

        #login .forget {
            font-size: 13px;
            text-align: center;
            display: block;
        }

        /*    --------------------------------------------------
            :: Inputs & Buttons
            -------------------------------------------------- */
        .form-control {
            color: #212121;
        }

        .btn-custom {
            color: #fff;
            background-color: #1fa67b;
        }

        .btn-custom:hover,
        .btn-custom:focus {
            color: #fff;
        }

        /*    --------------------------------------------------
            :: Footer
            -------------------------------------------------- */
        #footer {
            color: #6d6d6d;
            font-size: 12px;
            text-align: center;
        }

        #footer p {
            margin-bottom: 0;
        }

        #footer a {
            color: inherit;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Password Reset</h1>
        <p>
            Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
        </p>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-sm">Send Email And Reset The Password</button>
        </form>
    </div>

</body>
</html>

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Password Reset Complete</h1>
        <p>
            We've emailed you instructions for setting your password, if an account exists with the email you entered.
            You should receive them shortly.
            If you don't receive an email, please make sure you've entered the address you registered with, and check
            your spam folder. </p>
        <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-lg active"
           role="button" aria-pressed="true">Login</a>
    </div>

{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Enter new password</h1>
        <p>
        </p>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-sm">Reset Password</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Password Reset Sent</h1>
        <p>
            We've emailed you instructions for setting your password, if an account exists with the email you entered.
            You should receive them shortly.
            If you don't receive an email, please make sure you've entered the address you registered with, and check
            your spam folder. </p>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
{% trans "Thanks for using our site!" %}
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
{% endautoescape %}