RP/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from RP import views, settings

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('cr/', include('cr.urls')),
    path('home/', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ratings/', include('ratings.urls', namespace='ratings')),
    path('searchings/', include('searchings.urls', namespace='searchings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratings/urls.py
from django.urls import path

from . import views

app_name = 'ratings'
urlpatterns = [
    path('rating/<int:professor_id>/<str:professor_name>/', views.professor_rating,
         name='professor_rating'),
]

searchings/urls.py
from django.urls import path

from . import views

app_name = 'searchings'
urlpatterns = [
    path('<int:professor_id>/<str:professor_name>/', views.professor, name='professor'),
    path('school/<str:professor_school>/', views.school_filter, name='school_filter'),
    path('prof/<str:professor_name>/', views.professor_filter, name='professor_filter'),
    path('school_prof/<str:professor_school>/', views.school_professor_filter,
         name='school_professor_filter'),
    path('college_prof/<str:professor_college>/', views.college_professor_filter,
         name='college_professor_filter'),
]

searchings/models.py
from django.db import models
from django.contrib.auth.models import User


class Professor(models.Model):
    prof_name = models.CharField(max_length=30)
    prof_introduction = models.TextField()
    prof_school = models.ManyToManyField('School')
    prof_college = models.ManyToManyField('College')

    def __str__(self):
        return str(self.prof_name)


class School(models.Model):
    school_name = models.CharField(max_length=20)
    school_location = models.CharField(max_length=20, default='')
    school_introduction = models.TextField()

    def __str__(self):
        return self.school_name

    def __unicode__(self):
        return self.school_name


class College(models.Model):
    college_name = models.CharField(max_length=20)
    college_introduction = models.TextField()

    def __str__(self):
        return str(self.college_name)


class Major(models.Model):
    major_name = models.CharField(max_length=20)

    def __str__(self):
        return str(self.major_name)


class GeneralClass(models.Model):
    class_name = models.CharField(max_length=20)
    class_prof = models.ManyToManyField(Professor)
    class_college = models.ForeignKey(College, on_delete=models.CASCADE)
    class_major = models.ForeignKey("Major", on_delete=models.CASCADE)
    class_introduction = models.TextField()
    class_prerequisite = models.CharField(max_length=20)
    class_type = models.CharField(max_length=20)
    class_credit = models.FloatField()

    def __str__(self):
        return str(self.class_name)


class SpecificClass(models.Model):
    class_introduction = models.ForeignKey(GeneralClass, on_delete=models.CASCADE)
    class_section = models.IntegerField()
    class_code = models.IntegerField()
    class_period = models.CharField(max_length=20)
    class_remain_seat = models.IntegerField()

    def __str__(self):
        return self.class_introduction.class_name + '\n' + \
               str(self.class_introduction.class_prof) + '\n' + \
               str(self.class_introduction.class_college) + '\n' + \
               str(self.class_introduction.class_introduction) + '\n' + \
               str(self.class_section) + str(self.class_code) + '\n' + \
               str(self.class_remain_seat)


class Rating(models.Model):
    attendance_choices = (
        ('未知', "it's still a secret"),
        ('每周必点', "100% take attendance"),
        ('人少就点', "if there seems like not enough people"),
        ('基本不管', "doesn't really care the attendance"),
        ('纯看心情', "depends on the days or professor's mood"),
    )
    overall_rating = models.FloatField()
    overall_difficulty_number = models.FloatField()
    class_graded = models.CharField(max_length=5)
    overall_difficulty = models.CharField(max_length=100)
    overall_looking = models.CharField(max_length=20)
    attendance_requirement = models.CharField(max_length=30, choices=attendance_choices, default="未知")
    prof_personality_tag = models.CharField(max_length=50, null=True)
    student_learning_tag = models.CharField(max_length=50, null=True)
    class_atmosphere_tag = models.CharField(max_length=30, null=True)
    homework_requirement_tag = models.CharField(max_length=30, null=True)
    teaching_style_tag = models.CharField(max_length=30, null=True)
    prof_rating = models.ForeignKey('Professor', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.overall_rating) + '\n' + \
               str(self.overall_difficulty) + '\n' + \
               str(self.overall_looking) + '\n' + \
               str(self.class_graded) + '\n' + \
               str(self.attendance_requirement) + '\n' + \
               str(self.prof_personality_tag) + '\n' + \
               str(self.student_learning_tag) + '\n' + \
               str(self.class_atmosphere_tag) + '\n' + \
               str(self.homework_requirement_tag) + '\n' + \
               str(self.teaching_style_tag)


class Post(models.Model):
    post = models.TextField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    rating_post = models.ForeignKey('Rating', on_delete=models.CASCADE)

    def __str__(self):
        return self.post

searchings/forms.py
from django import forms
from .models import Post


class ProfessorForm(forms.ModelForm):
    post = forms.TextInput()

    class Meta:
        model = Post
        fields = ('post',)

searchings/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from home.forms import HomeForm
from searchings.forms import ProfessorForm
from searchings.models import Post, Professor, School, Rating, College


def professor(request, professor_id, professor_name):
    if request.method == "GET":
        form = HomeForm()
        print(form)
        prof = Professor.objects.get(id=professor_id)
        ratings = Rating.objects.filter(prof_rating=prof).order_by('-date')
        total = len(ratings)
        overall_grade = 0.0
        for score in ratings:
            overall_grade += score.overall_rating
        if total == 0:
            overall_grade = 0
        else:
            overall_grade = overall_grade / total
        overall_grade = round(overall_grade, 2)
        total_rating_user = len(ratings)
        posts = Post.objects.filter(rating_post__in=ratings).order_by('-date')
        args = {'form': form,
                'posts': posts,
                'prof': prof,
                'ratings': ratings,
                'overall_grade': overall_grade,
                'total_rating_user': total_rating_user,
                }
        return render(request, 'searchings/professor.html', args)

    if request.method == 'POST':
        form = HomeForm(request.POST)
        if form.is_valid():
            search = form.save(commit=False)
            search.save()
            school = form.cleaned_data['school']
            prof = form.cleaned_data['prof']
            college = form.cleaned_data['college']
            if school != '' and prof == '' and college == '':
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(school,)))
            elif school == '' and prof != '' and college == '':
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(prof,)))
            elif school == '' and prof == '' and college != '':
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(college,)))
            else:
                post = form.save(commit=False)
                post.user = request.user
                prof = Professor.objects.get(id=professor_id,
                                             prof_name=professor_name)

                ratings = Rating.objects.filter(prof_rating=prof).order_by('-date')
                for rating in ratings:
                    post.rating_post = rating
                post.save()
                args = {'form': form,
                        'prof': prof,
                        'ratings': ratings
                        }
                return render(request, 'searchings/professor.html', args)
        else:
            return redirect(reverse('searchings:professor', args=(professor_id, professor_name,)))


def professor_filter(request, professor_name):
    if request.method == "GET":
        form = HomeForm()
        profs = Professor.objects.filter(prof_name=professor_name)
        args = {'form': form,
                'profs': profs
                }
        if len(profs) == 0:
            profs = Professor.objects.filter(prof_name__startswith=professor_name)
            args = {'form': form,
                    'profs': profs,
                    }
            return render(request, 'searchings/professor_filter.html', args)
        if len(profs) > 1:
            return render(request, 'searchings/professor_filter.html', args)
        else:
            prof = Professor.objects.get(prof_name=professor_name)
            return HttpResponseRedirect(reverse('searchings:professor', args=(prof.id, professor_name,)))
    if request.method == 'POST':
        form = HomeForm(request.POST)
        if form.is_valid():
            search = form.save(commit=False)
            search.save()
            school = form.cleaned_data['school']
            prof = form.cleaned_data['prof']
            college = form.cleaned_data['college']
            if school != '' and prof == '' and college == '':
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(school,)))
            elif school == '' and prof != '' and college == '':
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(prof,)))
            elif school == '' and prof == '' and college != '':
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(college,)))
            else:
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(professor_name,)))


def school_filter(request, professor_school):
    if request.method == "GET":
        form = HomeForm()
        schools = School.objects.filter(school_name__startswith=professor_school)
        args = {'form': form,
                'schools': schools,
                }
        return render(request, 'searchings/school_filter.html', args)
    if request.method == 'POST':
        form = HomeForm(request.POST)
        if form.is_valid():
            search = form.save(commit=False)
            search.save()
            school = form.cleaned_data['school']
            prof = form.cleaned_data['prof']
            college = form.cleaned_data['college']
            if school != '' and prof == '' and college == '':
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(school,)))
            elif school == '' and prof != '' and college == '':
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(prof,)))
            elif school == '' and prof == '' and college != '':
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(college,)))
            else:
                return HttpResponseRedirect(reverse('searchings:school_filter', args=(professor_school,)))


def school_professor_filter(request, professor_school):
    if request.method == "GET":
        form = HomeForm()
        school = School.objects.filter(school_name__startswith=professor_school)
        profs = Professor.objects.filter(prof_school__in=school)
        args = {'form': form,
                'profs': profs
                }
        return render(request, 'searchings/professor_filter.html', args)
    if request.method == 'POST':
        form = HomeForm(request.POST)
        if form.is_valid():
            search = form.save(commit=False)
            search.save()
            school = form.cleaned_data['school']
            prof = form.cleaned_data['prof']
            college = form.cleaned_data['college']
            if school != '' and prof == '' and college == '':
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(school,)))
            elif school == '' and prof != '' and college == '':
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(prof,)))
            elif school == '' and prof == '' and college != '':
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(college,)))
            else:
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(professor_school,)))


def college_professor_filter(request, professor_college):
    if request.method == "GET":
        form = HomeForm()
        college = College.objects.filter(college_name__startswith=professor_college)
        profs = Professor.objects.filter(prof_college__in=college)
        args = {'form': form,
                'profs': profs
                }
        return render(request, 'searchings/professor_filter.html', args)
    if request.method == 'POST':
        form = HomeForm(request.POST)
        if form.is_valid():
            search = form.save(commit=False)
            search.save()
            school = form.cleaned_data['school']
            prof = form.cleaned_data['prof']
            college = form.cleaned_data['college']
            if school != '' and prof == '' and college == '':
                return HttpResponseRedirect(reverse('searchings:school_professor_filter', args=(school,)))
            elif school == '' and prof != '' and college == '':
                return HttpResponseRedirect(reverse('searchings:professor_filter', args=(prof,)))
            elif school == '' and prof == '' and college != '':
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(college,)))
            else:
                return HttpResponseRedirect(reverse('searchings:college_professor_filter', args=(professor_college,)))

searchings/templates/searchings/professor.html
{% extends 'base_search.html' %}
{% block head %}
{% endblock %}
{% block css %}
    {% load static %}
    <!-- Morris Charts CSS -->
    <link href="{% static 'searchings/vendor/morrisjs/morris.css' %}" rel="stylesheet">
    <link href="{% static 'searchings/progress_chart.css' %}" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet">
{% endblock %}

{% block body %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <!-- /.panel -->
                <div class="panel panel-default">
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h1>{{ prof.prof_name }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                            <small>已有 {{ total_rating_user }} 位同学评论过这个老师</small>
                                        </h1>
                                    </div>
                                    <div class="panel-body">
                                        <h3>学校：{% for school in prof.prof_school.all %}
                                            {{ school }}
                                        {% endfor %}
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                            学院：{% for college in prof.prof_college.all %}
                                                {{ college }}
                                            {% endfor %}</h3>
                                        <h3>参与课程：</h3>
                                        <h3>教学经验：24年</h3>
                                        <h3>基本资料：{{ prof.prof_introduction }}</h3>
                                        <pre>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                                                                             --{{ prof.prof_name }}</pre>
                                    </div>
                                    <!-- /.panel-body -->
                                </div>
                                <!-- /.panel -->
                            </div>
                            <!-- /.col-lg-4 (nested) -->
                            <div class="col-lg-4">
                                <div class="panel panel-default">
                                    <div class="panel-body">
                                        <div id="specificChart" class="donut-size">
                                            <div class="pie-wrapper">
                                                 <span class="label">
                                                <span class="num">0</span><span class="smaller"></span>
                                                         </span>
                                                <div class="pie">
                                                    <div class="left-side half-circle"></div>
                                                    <div class="right-side half-circle"></div>
                                                </div>
                                                <div class="shadow"></div>
                                            </div>
                                        </div>
                                        <a href="{% url 'ratings:professor_rating' prof.id prof.prof_name %}"
                                           class="btn btn-info btn-block"><h4>给咱老师评个分</h4></a>
                                    </div>
                                    <!-- /.panel-body -->
                                </div>
                            </div>
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>


        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Clients</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        All Clients
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <table id="dataTables-example" width="100%"
                               class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>总评</th>
                                <th>课程</th>
                                <th>对该老师的细节评价</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for rating in ratings %}
                                <tr>
                                    <th><h5>{{ rating.overall_rating }} 对老师的总体评价</h5>
                                        <h5>{{ rating.overall_difficulty }} 对老师上课的难度评价</h5></th>
                                    <th>课程</th>
                                    <th>对该老师的细节评价</th>
                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>总评</th>
                                <th>课程</th>
                                <th>对该老师的细节评价</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>

    </div>
    <!-- /#page-wrapper -->

{% endblock %}

{% block js %}
    {% load static %}
    <!-- Custom Theme JavaScript -->
    <script src="{% static 'searchings/dist/js/sb-admin-2.js' %}"></script>

    <!-- DataTables JavaScript -->
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable();
        });
    </script>
    <script>
        /**
         * Updates the donut chart's percent number and the CSS positioning of the progress bar.
         * Also allows you to set if it is a donut or pie chart
         * @param  {string}  el      The selector for the donut to update. '#thing'
         * @param  {number}  percent Passing in 22.3 will make the chart show 22%
         * @param  {boolean} donut   True shows donut, false shows pie
         */
        function updateDonutChart(el, percent, donut) {
            {#percent = Math.round(percent);#}
            if (percent > 5) {
                percent = 5;
            } else if (percent < 0) {
                percent = 0;
            }
            var deg = Math.round(360 * (percent / 5));

            if (percent > 2.5) {
                $(el + ' .pie').css('clip', 'rect(auto, auto, auto, auto)');
                $(el + ' .right-side').css('transform', 'rotate(180deg)');
            } else {
                $(el + ' .pie').css('clip', 'rect(0, 1em, 1em, 0.5em)');
                $(el + ' .right-side').css('transform', 'rotate(0deg)');
            }
            if (donut) {
                $(el + ' .right-side').css('border-width', '0.1em');
                $(el + ' .left-side').css('border-width', '0.1em');
                $(el + ' .shadow').css('border-width', '0.1em');
            } else {
                $(el + ' .right-side').css('border-width', '0.5em');
                $(el + ' .left-side').css('border-width', '0.5em');
                $(el + ' .shadow').css('border-width', '0.5em');
            }
            $(el + ' .num').text(percent);
            $(el + ' .left-side').css('transform', 'rotate(' + deg + 'deg)');
        }

        // Pass in a number for the percent
        updateDonutChart('#specificChart', {{ overall_grade }}, true);


        //Ignore the rest, it's for the input and checkbox

        $('#percent').change(function () {
            var percent = $(this).val();
            var donut = $('#donut input').is(':checked');
            updateDonutChart('#specificChart', percent, donut);
        }).keyup(function () {
            var percent = $(this).val();
            var donut = $('#donut input').is(':checked');
            updateDonutChart('#specificChart', percent, donut);
        });
        ;

        $('#donut input').change(function () {
            var donut = $('#donut input').is(':checked');
            var percent = $("#percent").val();
            if (donut) {
                $('#donut span').html('Donut');
            } else {
                $('#donut span').html('Pie');
            }
            updateDonutChart('#specificChart', percent, donut);
        });

    </script>

{% endblock %}


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>教师信息</title>#}
{#</head>#}
{#<body>#}
{#<h1>{{ prof.prof_name }}</h1>#}
{#{% for school in prof.prof_school.all %}#}
{#    <h1>{{ school }}</h1>#}
{#{% endfor %}#}
{#{% for college in prof.prof_college.all %}#}
{#    <h1>{{ college }}</h1>#}
{#{% endfor %}#}
{#<h1>{{ prof.prof_introduction }}</h1>#}
{#<a href="{% url 'ratings:professor_rating' prof.id prof.prof_name %}">Rate Your Professor</a>#}
{#{% for rating in ratings %}#}
{#    <h1>{{ rating }}</h1>#}
{#    <h3>{{ rating.date }}</h3>#}
{#    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}#}
{#    <form method="POST">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit">Submit</button>#}
{#    </form>#}
{#{% endfor %}#}
{#{% for post in posts %}#}
{#    {{ post.user }}#}
{#    {{ post.post }}#}
{#    <p>{{ post.date }}</p>#}
{#{% endfor %}#}
{##}
{#</body>#}
{#</html>#}

searchings/templates/searchings/school_filter.html
{% extends 'base_search.html' %}
{% block head %}

{% endblock %}
{% block css %}
    {% load static %}

    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <style>
        th a {
            display: block;
            border: 1px solid black;
            padding: 16px;
        }
    </style>
{% endblock %}

{% block body %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">所有相关的学校信息</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        所有相关的学校信息
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <table id="dataTables-example" width="100%"
                               class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>城市</th>
                                <th>介绍</th>
                                <th>名字</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for school in schools %}
                                <tr>
                                    <th>{{ school.school_location }}</th>
                                    <th>{{ school.school_introduction }}</th>
                                    <th><a href="{% url 'searchings:school_professor_filter' school.id school.school_name %}"
                                           class="btn btn-info btn-block">{{ school.school_name }}</a></th>
                                </tr>
                            {% endfor %}
                            </tbody>
                            {#                            <tfoot>#}
                            {#                            <tr>#}
                            {#                                <th>总评</th>#}
                            {#                                <th>课程</th>#}
                            {#                                <th>对该老师的细节评价</th>#}
                            {#                            </tr>#}
                            {#                            </tfoot>#}
                        </table>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>

    </div>
{% endblock %}

{% block js %}
    <!-- DataTables JavaScript -->
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable();
        })
        ;
    </script>
{% endblock %}














<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>教师信息</title>
</head>
<body>

{% for prof in profs %}
    <h1>{{ prof.prof_name }}</h1>
    {% for school in prof.prof_school.all %}
        <h1>{{ school }}</h1>
    {% endfor %}
    {% for college in prof.prof_college.all %}
        <h1>{{ college }}</h1>
    {% endfor %}
    <a href="{% url 'home:professor' prof.prof_id prof.prof_name %}">HELLO</a>
{% endfor %}


</body>
</html>